# Generated by Django 4.1.7 on 2023-04-05 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.AlterField(
            model_name='dislikes',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.video'),
        ),
        migrations.AlterField(
            model_name='dislikes',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.video'),
        ),
        migrations.AlterField(
            model_name='history',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.video'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
