# Generated by Django 4.1.7 on 2023-04-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_remove_video_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='id_video',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='dislikes',
            old_name='id_video',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='id_video',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='id_video',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='videoimage',
            old_name='id_video',
            new_name='video',
        ),
    ]
