# Generated by Django 4.1.7 on 2023-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_id_video_comments_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoimage',
            name='video',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='default_avatar.jpg', max_length=400, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.CharField(default=2, max_length=400, verbose_name='Превью'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
        migrations.DeleteModel(
            name='VideoImage',
        ),
    ]
