# Generated by Django 4.1.7 on 2023-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.CharField(max_length=400, null=True, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
