# Generated by Django 4.1.7 on 2023-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_video_description_alter_video_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publiched',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
