# Generated by Django 4.1.7 on 2023-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_publiched_video_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislikes',
            options={'verbose_name': 'Дизлайк', 'verbose_name_plural': 'Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='Default description', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Default title', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='dislikes',
            unique_together={('username', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('username', 'video')},
        ),
    ]
